language: python
python:
    - "2.7"
    - "3.3"
    - "pypy"
install:
    - pip install coveralls
    - pip install -r requirements.txt
script:
    - coverage run --source=photoriver setup.py test
after_success:
    - coveralls
